import logging
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from src.agents.state import AgentState
from src.llm_factory import get_main_brain
from src.services.socket_manager import socket_manager

logger = logging.getLogger(__name__)

class ReviewResult(BaseModel):
    approved: bool = Field(description="Set to True if the code looks good and functional. False if it needs fixes.")
    feedback: str = Field(description="Detailed feedback on what is wrong and how to fix it. If approved, leave empty or give praise.")

async def reviewer_node(state: AgentState):
    project_id = state.get('project_id')
    artifacts = state.get('generated_artifacts', {})
    iteration = state.get('iteration_count', 0)
    
    logger.info(f"REVIEWER: Starting review (Iteration {iteration + 1})")

    # If no artifacts (e.g. just planning), skip review
    if not artifacts:
        return {"status": "approved"}

    # Notify UI
    await socket_manager.broadcast(project_id, {
        "type": "status",
        "message": f"Quality Control Agent is reviewing the code (Attempt {iteration + 1})..."
    })

    llm = get_main_brain()
    structured_llm = llm.with_structured_output(ReviewResult)

    # Prepare context for review
    code_summary = ""
    for task_id, content in artifacts.items():
        code_summary += f"\n--- Task {task_id} Output ---\n{content[:2000]}..." # Truncate for context window if huge

    system_prompt = """You are a Senior Staff Engineer and Code Reviewer at Google.
    Your job is to strictly validate the code generated by junior agents.
    
    CRITERIA:
    1. Syntax: Is the code valid Python/JS/HTML?
    2. Logic: Does it actually solve the user's request?
    3. Completeness: Are there placeholders like 'TODO' or 'pass'? (Reject if crucial logic is missing).
    
    If the code is broken or lazy, REJECT it and provide specific instructions for the worker to fix it.
    If it looks decent for an MVP, APPROVE it.
    """

    try:
        response: ReviewResult = await structured_llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"User Request: {state['user_request']}\n\nGenerated Code:\n{code_summary}")
        ])

        logger.info(f"REVIEWER DECISION: Approved={response.approved}")

        if not response.approved:
             await socket_manager.broadcast(project_id, {
                "type": "status",
                "message": f"Reviewer rejected the code. Sending back for fixes..."
            })
        else:
             await socket_manager.broadcast(project_id, {
                "type": "status",
                "message": "Code approved! Finalizing build..."
            })

        # FIX: If approved, ensure feedback is empty to stop the graph loop
        final_feedback = response.feedback
        if response.approved:
            final_feedback = ""

        return {
            "review_feedback": final_feedback,
            "iteration_count": iteration + 1,
            # We don't change 'status' here, the graph edge condition will handle it
        }

    except Exception as e:
        logger.error(f"Review failed: {e}")
        # On error, default to approved to avoid infinite stuck loops
        return {"review_feedback": "Reviewer crashed, skipping checks.", "iteration_count": iteration + 1}

